name: Build benchmarks

on:
  schedule:
    - cron: '0 22 * * 4' # runs at 00:00 CET Thursday

  pull_request:
    branches: [ "master" ]

jobs:
          
  build_pr_scheduling:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Compile HW Partial Reconfig Scheduling
      run: |
        mkdir build_pr_scheduling_hw && cd build_pr_scheduling_hw
        /usr/bin/cmake ../hw/ -DFDEV_NAME=u55c -DEXAMPLE=pr_scheduling -DACLK_F=250
        make shell && make compile

    - name: Compile SW Partial Reconfig Scheduling
      run: |
        mkdir build_pr_scheduling_sw && cd build_pr_scheduling_sw
        /usr/bin/cmake ../sw/examples/pr_scheduling/
        make
