name: Coyote CI

on:
  push:
    branches: [ master ]

env:
  PATH: "/mnt/scratch/tools_tmp/Xilinx/Vivado/2021.2/bin:/sbin:/usr/sbin:/bin:/usr/bin"

jobs:
  build_bmark_host:
    runs-on: [self-hosted, linux]
    steps:
    - uses: actions/checkout@master
      with:
        submodules: 'recursive'
        
    - name: Config
      run: |
        cd hw && mkdir build_bmark_host && cd build_bmark_host
        cmake ../ -DFDEV_NAME=u280 -DEXAMPLE=bmark_host

    - name: Create project
      run: |
        make shell

  build_bmark_fpga:
    runs-on: [self-hosted, linux]
    steps:
    - uses: actions/checkout@master
      with:
        submodules: 'recursive'
        
    - name: Config
      run: |
        cd hw && mkdir build_bmark_fpga && cd build_bmark_fpga
        cmake ../ -DFDEV_NAME=u280 -DEXAMPLE=bmark_fpga

    - name: Create project
      run: |
        make shell

