name: Build benchmarks

on:
  schedule:
    - cron: '0 22 * * *' # runs at 00:00 CET

  pull_request:
    branches: [ "master" ]

jobs:

  build_bmark_host:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    
    - name: Compile HW Benchmark Host Example
      run: |
        mkdir build_bmark_host_hw && cd build_bmark_host_hw
        /usr/bin/cmake ../hw/ -DFDEV_NAME=u55c -DEXAMPLE=bmark_host
        make shell && make compile
    
    - name: Compile SW Benchmark Host Example
      run: |
        mkdir build_bmark_host_sw && cd build_bmark_host_sw
        /usr/bin/cmake ../sw/examples/bmark_host/
        make
        
  build_gbm_dtrees:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Compile HW gradient boosting dtrees
      run: |
        mkdir build_gbm_dtrees_ && cd build_gbm_dtrees
        /usr/bin/cmake ../hw/ -DFDEV_NAME=u55c -DEXAMPLE=gbm_dtrees
        make shell && make compile
        
  build_hyper_log_log:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Compile Hyperloglog
      run: |
        mkdir build_hyper_log_log && cd build_hyper_log_log
        /usr/bin/cmake ../hw/ -DFDEV_NAME=u55c -DEXAMPLE=hyper_log_log
        make shell && make compile
  
  build_service_aes:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Compile service AES
      run: |
        mkdir build_service_aes && cd build_service_aes
        /usr/bin/cmake ../hw/ -DFDEV_NAME=u55c -DEXAMPLE=service_aes
        make shell && make compile
        
  build_rdma_host:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Compile RDMA host
      run: |
        mkdir build_rdma_host && cd build_rdma_host
        /usr/bin/cmake ../hw/ -DFDEV_NAME=u55c -DEXAMPLE=rdma_host -DPMTU_BYTES=1408
        make shell && make compile
        
  build_tcp:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Compile TCP/IP
      run: |
        mkdir build_tcp && cd build_tcp
        /usr/bin/cmake ../hw/ -DFDEV_NAME=u55c -DEXAMPLE=tcp -DACLK_F=250
        make shell && make compile
          
  build_pr_scheduling:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Compile PR scheduling
      run: |
        mkdir build_pr_scheduling && cd build_pr_scheduling
        /usr/bin/cmake ../hw/ -DFDEV_NAME=u55c -DEXAMPLE=pr_scheduling -DACLK_F=250
        make shell && make compile
